Player:
  Template:
    base-health: 20.0
    base-healthRegen: 2.0
    base-damage: 5.0
    base-armor: 3.0
    base-crit: 2.0
    base-dodge: 2.0
    base-attack-speed: 1.0
    base-crit-damage.multiplier: 1.5
    base-movement-speed: 2.0
Item:
  Attributes:
    Health:
      keyword: health
    Damage:
      keyword: damage
    Health-Regen:
      keyword: regen
    Dodge:
      keyword: dodge
    Critical:
      keyword: crit-chance
    Armor:
      keyword: armor
    Exp:
      keyword: exp
    Attack-Speed:
      keyword: attack-speed
    Movement-Speed:
      keyword: movement-speed